apiVersion: v1
kind: Service
metadata:
  name: {{ include "kafka.headless" . }}
  labels:
    {{- include "kafka.labels" . | nindent 4 }}
spec:
  clusterIP: None
  type: ClusterIP
  ports:
    - port: {{ .Values.service.port }}
      targetPort: brokerport
      protocol: TCP
      name: brokerport
  selector:
    {{- include "kafka.selectorLabels" . | nindent 4 }}
