apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "pg-data.fullname" . }}-sql
  labels:
  {{- include "pg-data.labels" . | nindent 4 }}
data:
{{- range $path, $_ := .Files.Glob "files/sql/*.sql" }}

{{ $path | trimPrefix "files/sql/" | indent 2}}: |-
{{ $.Files.Get $path | indent 4}}
{{ end }}