apiVersion: v1
kind: Service
metadata:
  name: {{ include "cassandra.fullname" . }}
  labels:
    {{- include "cassandra.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: cql
      protocol: TCP
      name: cql
  selector:
    {{- include "cassandra.selectorLabels" . | nindent 4 }}
