apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "postgres.fullname" . }}-certs
  labels:
  {{- include "postgres.labels" . | nindent 4 }}
binaryData:
{{- range $path, $_ := .Files.Glob "files/certs/*" }}
{{ $path | trimPrefix "files/certs/" | indent 2 }}: |-
{{ $.Files.Get $path | b64enc | indent 4}}
{{ end }}

