{{if .Values.pvc.enabled -}}
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: {{ include "postgres.fullname" . }}-data
  labels:
  {{- include "postgres.labels" . | nindent 4 }}
spec:
  accessModes:
    - {{ .Values.pvc.accessMode | quote }}
  resources:
    requests:
      storage: {{ .Values.pvc.storage | quote}}
  storageClassName: {{ .Values.pvc.storageClass | quote}}
  volumeMode: Filesystem

  {{ end -}}
