apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "cass-data.fullname" . }}-cql
  labels:
  {{- include "cass-data.labels" . | nindent 4 }}
data:
{{- range $path, $_ := .Files.Glob "files/cql/*.cql" }}

{{ $path | trimPrefix "files/cql/" | indent 2}}: |-
{{ $.Files.Get $path | indent 4}}
{{ end }}