apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "cass-data.fullname" . }}-sh
  labels:
  {{- include "cass-data.labels" . | nindent 4 }}
data:
{{- range $path, $_ := .Files.Glob "files/scripts/*.sh" }}
{{ $path | trimPrefix "files/scripts/" | indent 2 }}: |-
{{ $.Files.Get $path | indent 4}}
{{ end }}