apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "k8s-read.fullname" . }}-config
  labels:
  {{- include "k8s-read.labels" . | nindent 4 }}
data:
{{- range $path, $_ := .Files.Glob "files/*.json" }}

{{ $path | trimPrefix "files/" | indent 2}}: |-
{{ $.Files.Get $path | indent 4}}
{{ end }}
