kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: kube-read-cluster-role-binding
  labels:
    {{- include "k8s-read.labels" . | nindent 4 }}
subjects:
  - kind: ServiceAccount
    name: kube-api-reader
    namespace: default
roleRef:
  kind: ClusterRole
  name: kube-read-cluster-role
  apiGroup: rbac.authorization.k8s.io

