apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: kube-read-role
  labels:
    {{- include "k8s-read.labels" . | nindent 4 }}
rules:
  - apiGroups:
      - ""
    resources:
      - pods
      - pods/log
      - services
      - services/finalizers
      - endpoints
      - persistentvolumeclaims
      - configmaps
    verbs:
      - get
      - list
      - watch

  - apiGroups:
      - apps
    resources:
      - deployments
      - daemonsets
      - replicasets
      - statefulsets
    verbs:
      - get
      - list
      - watch
  - apiGroups:
      - extensions
    resources:
      - deployments
    verbs:
      - get
      - list
      - watch

  - apiGroups:
      - batch
    resources:
      - jobs
    verbs:
      - get
      - list
      - watch

  - apiGroups:
      - monitoring.coreos.com
    resources:
      - servicemonitors
    verbs:
      - get
      - list
      - watch


