apiVersion: v1
kind: Service
metadata:
  name: {{ include "ks8-read.fullname" . }}
  labels:
    {{- include "ks8-read.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.portName }}
      protocol: TCP
      name: {{ .Values.service.portName }}
      nodePort: {{ .Values.service.nodePort }}
  selector:
    {{- include "ks8-read.selectorLabels" . | nindent 4 }}
