apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: servicemonitor-read-role
  labels:
    {{- include "ks8-read.labels" . | nindent 4 }}
rules:
  - apiGroups:
      - monitoring.coreos.com
    resources:
      - servicemonitors
    verbs:
      - get
      - list
      - watch


