kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: servicemonitor-read-role-binding
  labels:
    {{- include "k8s-read.labels" . | nindent 4 }}
subjects:
  - kind: ServiceAccount
    name: kube-api-reader
roleRef:
  kind: Role
  name: servicemonitor-read-role
  apiGroup: rbac.authorization.k8s.io
